### ISSUE TITLE
Issue: The "+Add New List" displays incorrectly in Google Chrome (Windows 8.1)

### ISSUE THREAD

**Issue by fortchagos** [galenmaly/lighterpack#65]
The popup menu list does not display correctly in Google Chrome running on Windows.  The popup displays but any attempts to use the scroll bar to display lower menu items cause the entire popup to flicker.  Scrolling to lower menu items is impossible (but the menu items display are selectable - even the one that's partially shown).

![addnewlistinchromeerror](https://cloud.githubusercontent.com/assets/25619764/25983321/0a1c05da-36b2-11e7-9705-04f5c30a1b53.png)

**Comment by johnabela** [comment]
I am running W10, Google Chrome, 58.0.3029.110 (64-bit), and I cannot duplicate this issue.

**Comment by fortchagos** [comment]
Fortunately, with the wheel mouse I can still scroll up and down through the menu.  It's weird, perhaps a widget set issue.

**Comment by galenmaly** [comment]
This is fixed in the rewrite.  Lessons leaned about the quality of pull requests to accept.

**Comment by makergabriel** [comment]
> This is fixed in the rewrite. Lessons leaned about the quality of pull requests to accept.

<img width="322" alt="Screen Shot 2019-05-08 at 7 23 50 PM" src="https://user-images.githubusercontent.com/30101956/57422920-87b1e200-71d7-11e9-9948-4fa3ce07fb0d.png">

I still see this issue when only one list exists using Chrome on mac.  Removing the   overflow-y: auto;
from #listContainer seems to resolve it locally on the vue branch.

<img width="312" alt="Screen Shot 2019-05-08 at 9 24 22 PM" src="https://user-images.githubusercontent.com/30101956/57422989-b8921700-71d7-11e9-817a-68c31737b41f.png">

**Comment by galenmaly** [comment]
Curious, wonder what happened there.

In any case, I was adding popover component and brought that over here too:

<img width="231" alt="new-list" src="https://user-images.githubusercontent.com/7111499/57540724-33575100-7302-11e9-96a2-ad3065fcee8e.png">

**Comment by galenmaly** [comment]
Fixed in prod
